const pool = require('../config/database');

const schema = process.env.DB_SCHEMA || 'administradorcocina';

// Mapeo de productos a proveedores basado en los datos proporcionados
const proveedoresMapping = {
  // BODEGA NEJAPA
  'BODEGA NEJAPA': [
    'ACEITE COMESTIBLE ORISOL', 'AZUCAR BLANCA REFINADA', 'BANDEJA DESCARTABLE N 8',
    'BOLSA TRANSPARENTE 5 LIBRAS', 'BOLSA TRANSPARENTE 17X21', 'BOLSA TRANSPARENTE 22X32',
    'BOLSA TRANSPARENTE 34X50', 'CAFÉ MOLIDO', 'CUCHARA DESC', 'CUCHARA SOPERA',
    'CUCHILLO DESCARTABLE', 'GORROS', 'GUANTES DE NITRILO', 'JABON LIQUIDO',
    'MASCARILLAS DE AMARRAR', 'PAPEL ROLL EXTENDER', 'PAPEL TOALLA TIPO MAYORDOMO',
    'PAPEL TORK CON PLUG', 'PAPEL DE TOALLA DE MANOS TORK', 'PLATO DESCARTABLE N° 9',
    'POLIPEL', 'SAL INDUSTRIAL REFINADA', 'SERVILLETAS KIMLARK', 'SOPERO DESCARTABLE N° 32',
    'TENEDOR DESCARTABLE GRANDE', 'VASO DESCARTABLE No 8', 'LEGIA MAGIA BLANCA',
    'ALKEMY CB 401', 'STRIPER', 'EXTRA CLEAN', 'SANIGIZER PLUS', 'JABON DE MANOS PLUS FREE FOAM',
    'ALCOHOL DE MANOS DES-E', 'ACTIGEL', 'XY12', 'BIOSAP'
  ],
  // VERDURAS Y FRUTAS RIVAS
  'VERDURAS Y FRUTAS RIVAS': [
    'AGUACATES', 'AJO', 'ALCAPATE', 'APIO', 'AYOTES', 'BROCOLI', 'CEBOLLA BLANCA',
    'CEBOLLAS BLANCAS', 'CHILE CIRUELA', 'CHILE GUAJO', 'CHILE VERDE', 'CHILE JALAPEÑOS',
    'CHILES ROJOS Y AMARILLO', 'CHIPILÍN', 'CILANTRO', 'EJOTE', 'ELOTES CRIOLLOS',
    'ESPINACAS', 'GUISQUIL CHAPIN', 'HOJA DE HUERTA', 'JAMAICA', 'JENGIBRE',
    'LECHUGAS REPOLLADAS', 'LIMONES', 'LOROCO', 'MANTECA DE CERDO', 'PAPA SOLOMA',
    'PEPINOS', 'PIPIANES', 'PLATANOS', 'RABANOS', 'REPOLLOS', 'RETOÑOS DE SOYA',
    'TOMATES DE COCINA', 'TOMATES PARA SALSA', 'YUCA', 'ZANAHORIA', 'BANANOS',
    'GUAYABAS', 'MANZANA GALA', 'MANZANA ROJAS', 'MELONES', 'PAPAYAS', 'PIÑAS GOLDEN',
    'SANDIAS', 'TAMARINDO', 'UVAS'
  ],
  // SUPER SELECTOS - ARTICULOS DE LIMPIEZA
  'ARTICULOS DE LIMPIEZA': [
    'DESINFECTANTE FABULOSO MANZANA', 'DETERGENTE DANY 10K', 'FIBRA METALICA GRANDE',
    'FIBRA VERDE SCOTH BRITE', 'LAVAPLATOS SELECTOS', 'LAVAPLATOS LIQUIDO AXION',
    'TOALLA PARA TRAPEADOR'
  ],
  // SUPER SELECTOS - CARNES ROJAS
  'CARNES ROJAS': [
    'ALETA', 'BISTECK DE RES AL MINUTO', 'CARNE MOLIDA SUPER ESPECIAL',
    'COSTILLA ALTA DE RES', 'GATO DE RES', 'GUISO DE RES ESPECIAL'
  ],
  // SUPER SELECTOS - EMBUTIDOS
  'EMBUTIDOS': [
    'CHORIZO PAMPERO', 'CHORIZO ARGENTINO DANY', 'CHORIZO MEXICANO DANY',
    'FILETE DE PESCADO', 'JAMÓN FAMILIAR', 'JAMÓN VIRGINIA DANY', 'LONGANIZA CAMPESTRE TOLEDO',
    'SALCHICHA HOTDOG', 'SALCHICHA DE PAVO DANY'
  ],
  // SUPER SELECTOS - FRUTAS Y VERDURAS
  'FRUTAS Y VERDURAS': [
    'LECHUGA PALMITO', 'LECHUGA ROMANA', 'MELON', 'REPOLLO MORADO'
  ],
  // SUPER SELECTOS - General (productos que no son de los sub-proveedores)
  'SUPER SELECTOS': [
    'AJO EN POLVO BADIA', 'ARROZ PRECOCIDO SAN FRANCISCO', 'AVENA EN HOJUELAS QUAKER',
    'BOLSA SANDWICHERA 2LBS', 'CANELA EN RAJA', 'CONSOME CARNE LA FAMILIA',
    'CONSOME CARNE ROBERTONI', 'CONSOME DE POLLO ROBERTONI', 'CHAOMEIN CON SOYA DRAGON',
    'ESPAGUETTIS FAMA', 'CODITOS FMA', 'CHILE JALISCO', 'CHOCOLATE EN TABLILLA',
    'ENCENDEDOR BIC', 'FIDEO PARMESSANA EN TIRA', 'FRIJOL ROJO DE SEDA DON FRIJOL',
    'FLAN DE VAINILLA LA FAMILIA', 'GELATINAS DE SABORES', 'LECHE EN POLVO DOS PINOS',
    'HARINA DE MAÍZ MASECA', 'HARINA TODO USO FLORA', 'MAYONESA PURA MCCORMICK',
    'MOSTAZA MCCOMIRCK', 'MOSTAZA REGIA', 'MAIZENA ATOL BANANO', 'MAIZENA ATOL VAINILLA',
    'MAIZENA NATURAL', 'MAIZENA ATOL FRESA', 'MAIZENA ATOL MANZANA CANELA', 'MIGA DE PAN',
    'PASTA ROMA ESPAGUETTI', 'PASTA LASAGNA INA', 'POLVO PARA HORNEAR', 'PAN CROISSANT SIMPLE',
    'PAN ARABE BAKERY PEQUEÑO', 'PAPEL ALUMINIO SELECTOS', 'PIMIENTA NEGRA MOLIDA BADIA',
    'REMOVEDOR DE CAFÉ', 'RAPIDITAS BIMBO', 'SALSA BARBACOA KRAFT ORIGINAL',
    'SALSA DE TOMATE DEL MONTE', 'SALSA BARBACOA KRAFT SMOKE', 'SALSA INGLESA REGGI',
    'SALSA VERDE CLEMENTE', 'SALSA VERDE B&B', 'SALSA DE SOYA', 'SOPA MAGGI POLLO CON FIDEOS',
    'SOPA MAGGI COLA DE RES', 'SAZON COMPLETO BADIA', 'SUPER TISTE PROINCA', 'TANG VARIEDAD DE SABORES',
    'VINAGRE DE MANZANA', 'VINAGRE DE MANZANA CLEMENTE', 'VINAGRE BLANCO CLEMENTE',
    'VAINILLA OSCURA LA FAMILIA'
  ],
  // LACTEOS
  'LACTEOS': [
    'MOZZARELLA RALLADO', 'REQUESON', 'CREMA MINI PORCION', 'QUESILLO BLOCK',
    'QUESO MANTEQUILLA BLOCK', 'CREMA ESPECIAL GRANEL'
  ],
  // AVICOLA SALVADOREÑA
  'AVICOLA SALVADOREÑA': [
    'POLLOS EN MITAD SIN ALAS', 'PAVIPOLLO PEQUEÑO', 'BOLSA DE POLLOS EN MITADES',
    'RECORTES DE PECHUGA', 'PECHUGAS DESHUESADAS'
  ],
  // ARROCERA SAN FRANCISCO
  'ARROCERA SAN FRANCISCO': [
    'FRIJOL ROJO SAN FRANCISCO GRANEL', 'ARROZ PRE COCIDO SAN FRANCISCO',
    'ARROZ BLANCO 5 ESTRELLAS', 'HARINA DE ARROZ'
  ],
  // LA NUEVA AVICOLA
  'LA NUEVA AVICOLA': [
    'HUEVOS MEDIANOS'
  ],
  // TORTILLAS
  'TORTILLAS': [
    'TORTILLAS'
  ],
  // TROPIGAS
  'TROPIGAS': [
    'CILINDROS DE GAS 25 LIBRAS'
  ]
};

async function updateProveedores() {
  try {
    console.log('Actualizando proveedores en productos...');
    
    for (const [proveedor, productos] of Object.entries(proveedoresMapping)) {
      for (const producto of productos) {
        // Buscar coincidencias parciales en la descripción
        const query = `
          UPDATE ${schema}.productos 
          SET proveedor = $1 
          WHERE descripcion ILIKE $2 AND (proveedor IS NULL OR proveedor = '')
        `;
        await pool.query(query, [proveedor, `%${producto}%`]);
      }
      console.log(`Actualizados productos de: ${proveedor}`);
    }
    
    // Verificar productos sin proveedor
    const result = await pool.query(`
      SELECT descripcion FROM ${schema}.productos 
      WHERE proveedor IS NULL OR proveedor = ''
      ORDER BY descripcion
    `);
    
    if (result.rows.length > 0) {
      console.log('\nProductos sin proveedor asignado:');
      result.rows.forEach(row => console.log(`- ${row.descripcion}`));
    } else {
      console.log('\nTodos los productos tienen proveedor asignado.');
    }
    
    console.log('\n¡Actualización completada!');
    process.exit(0);
  } catch (error) {
    console.error('Error actualizando proveedores:', error);
    process.exit(1);
  }
}

updateProveedores();
